using NUnit.Framework;

namespace Bindables.Windows.Test;

public abstract partial class WindowsAttachedPropertyTests<T>
{
	[Test]
	public void RegularProperty()
	{
		const string sourceCodeTemplate = @"
using PlatformNamespace;
using AttributeNamespace;

public partial class ExampleClass
{
	private static readonly string DefaultValue = ""Test"";

	[AttachedProperty(typeof(int))]
	public static readonly PropertyType Example1Property;

	[AttachedProperty(typeof(int), OnPropertyChanged = nameof(PropertyChangedCallback))]
	public static readonly PropertyType Example2Property;

	[AttachedProperty(typeof(string), DefaultValueField = nameof(DefaultValue))]
	public static readonly PropertyType Example3Property;

	[AttachedProperty(typeof(string), Options = FrameworkPropertyMetadataOptions.BindsTwoWayByDefault)]
	public static readonly PropertyType Example4Property;

	[AttachedProperty(typeof(string), OnPropertyChanged = nameof(PropertyChangedCallback), DefaultValueField = nameof(DefaultValue))]
	public static readonly PropertyType Example5Property;

	[AttachedProperty(typeof(string), OnPropertyChanged = nameof(PropertyChangedCallback), DefaultValueField = nameof(DefaultValue), Options = FrameworkPropertyMetadataOptions.BindsTwoWayByDefault)]
	public static readonly PropertyType Example6Property;

	[AttachedProperty(typeof(int), OnCoerceValue = nameof(CoerceValueCallback))]
	public static readonly PropertyType Example7Property;

	[AttachedProperty(typeof(int), OnPropertyChanged = nameof(PropertyChangedCallback), OnCoerceValue = nameof(CoerceValueCallback))]
	public static readonly PropertyType Example8Property;

	[AttachedProperty(typeof(string), OnCoerceValue = nameof(CoerceValueCallback), DefaultValueField = nameof(DefaultValue))]
	public static readonly PropertyType Example9Property;

	[AttachedProperty(typeof(string), OnPropertyChanged = nameof(PropertyChangedCallback), OnCoerceValue = nameof(CoerceValueCallback), DefaultValueField = nameof(DefaultValue))]
	public static readonly PropertyType Example10Property;

	[AttachedProperty(typeof(string), OnCoerceValue = nameof(CoerceValueCallback), DefaultValueField = nameof(DefaultValue), Options = FrameworkPropertyMetadataOptions.BindsTwoWayByDefault)]
	public static readonly PropertyType Example11Property;

	[AttachedProperty(typeof(string), OnPropertyChanged = nameof(PropertyChangedCallback), OnCoerceValue = nameof(CoerceValueCallback), DefaultValueField = nameof(DefaultValue), Options = FrameworkPropertyMetadataOptions.BindsTwoWayByDefault)]
	public static readonly PropertyType Example12Property;

	private static void PropertyChangedCallback(BaseClassName obj, DependencyPropertyChangedEventArgs args)
	{
	}

	private static object CoerceValueCallback(BaseClassName obj, object value)
	{
		return """";
	}
}";

		const string expectedSourceCodeTemplate = @"
// Generated by Bindables
using PlatformNamespace;

#nullable enable

public partial class ExampleClass
{
    public static int GetExample1(BaseClassName target)
    {
        return (int)target.GetValue(Example1Property);
    }

    public static void SetExample1(BaseClassName target, int value)
    {
        target.SetValue(Example1Property, value);
    }

    public static int GetExample2(BaseClassName target)
    {
        return (int)target.GetValue(Example2Property);
    }

    public static void SetExample2(BaseClassName target, int value)
    {
        target.SetValue(Example2Property, value);
    }

    public static string? GetExample3(BaseClassName target)
    {
        return (string?)target.GetValue(Example3Property);
    }

    public static void SetExample3(BaseClassName target, string? value)
    {
        target.SetValue(Example3Property, value);
    }

    public static string? GetExample4(BaseClassName target)
    {
        return (string?)target.GetValue(Example4Property);
    }

    public static void SetExample4(BaseClassName target, string? value)
    {
        target.SetValue(Example4Property, value);
    }

    public static string? GetExample5(BaseClassName target)
    {
        return (string?)target.GetValue(Example5Property);
    }

    public static void SetExample5(BaseClassName target, string? value)
    {
        target.SetValue(Example5Property, value);
    }

    public static string? GetExample6(BaseClassName target)
    {
        return (string?)target.GetValue(Example6Property);
    }

    public static void SetExample6(BaseClassName target, string? value)
    {
        target.SetValue(Example6Property, value);
    }

    public static int GetExample7(BaseClassName target)
    {
        return (int)target.GetValue(Example7Property);
    }

    public static void SetExample7(BaseClassName target, int value)
    {
        target.SetValue(Example7Property, value);
    }

    public static int GetExample8(BaseClassName target)
    {
        return (int)target.GetValue(Example8Property);
    }

    public static void SetExample8(BaseClassName target, int value)
    {
        target.SetValue(Example8Property, value);
    }

    public static string? GetExample9(BaseClassName target)
    {
        return (string?)target.GetValue(Example9Property);
    }

    public static void SetExample9(BaseClassName target, string? value)
    {
        target.SetValue(Example9Property, value);
    }

    public static string? GetExample10(BaseClassName target)
    {
        return (string?)target.GetValue(Example10Property);
    }

    public static void SetExample10(BaseClassName target, string? value)
    {
        target.SetValue(Example10Property, value);
    }

    public static string? GetExample11(BaseClassName target)
    {
        return (string?)target.GetValue(Example11Property);
    }

    public static void SetExample11(BaseClassName target, string? value)
    {
        target.SetValue(Example11Property, value);
    }

    public static string? GetExample12(BaseClassName target)
    {
        return (string?)target.GetValue(Example12Property);
    }

    public static void SetExample12(BaseClassName target, string? value)
    {
        target.SetValue(Example12Property, value);
    }

    static ExampleClass()
    {
        Example1Property = PropertyType.RegisterAttached(
            ""Example1"",
            typeof(int),
            typeof(ExampleClass),
            new FrameworkPropertyMetadata());
        
        Example2Property = PropertyType.RegisterAttached(
            ""Example2"",
            typeof(int),
            typeof(ExampleClass),
            new FrameworkPropertyMetadata(PropertyChangedCallback));
        
        Example3Property = PropertyType.RegisterAttached(
            ""Example3"",
            typeof(string),
            typeof(ExampleClass),
            new FrameworkPropertyMetadata(DefaultValue));
        
        Example4Property = PropertyType.RegisterAttached(
            ""Example4"",
            typeof(string),
            typeof(ExampleClass),
            new FrameworkPropertyMetadata(default, (FrameworkPropertyMetadataOptions)256));
        
        Example5Property = PropertyType.RegisterAttached(
            ""Example5"",
            typeof(string),
            typeof(ExampleClass),
            new FrameworkPropertyMetadata(DefaultValue, PropertyChangedCallback));
        
        Example6Property = PropertyType.RegisterAttached(
            ""Example6"",
            typeof(string),
            typeof(ExampleClass),
            new FrameworkPropertyMetadata(DefaultValue, (FrameworkPropertyMetadataOptions)256, PropertyChangedCallback));
        
        Example7Property = PropertyType.RegisterAttached(
            ""Example7"",
            typeof(int),
            typeof(ExampleClass),
            new FrameworkPropertyMetadata(default, CoerceValueCallback));
        
        Example8Property = PropertyType.RegisterAttached(
            ""Example8"",
            typeof(int),
            typeof(ExampleClass),
            new FrameworkPropertyMetadata(PropertyChangedCallback, CoerceValueCallback));
        
        Example9Property = PropertyType.RegisterAttached(
            ""Example9"",
            typeof(string),
            typeof(ExampleClass),
            new FrameworkPropertyMetadata(DefaultValue, default, CoerceValueCallback));
        
        Example10Property = PropertyType.RegisterAttached(
            ""Example10"",
            typeof(string),
            typeof(ExampleClass),
            new FrameworkPropertyMetadata(DefaultValue, PropertyChangedCallback, CoerceValueCallback));
        
        Example11Property = PropertyType.RegisterAttached(
            ""Example11"",
            typeof(string),
            typeof(ExampleClass),
            new FrameworkPropertyMetadata(DefaultValue, (FrameworkPropertyMetadataOptions)256, default, CoerceValueCallback));
        
        Example12Property = PropertyType.RegisterAttached(
            ""Example12"",
            typeof(string),
            typeof(ExampleClass),
            new FrameworkPropertyMetadata(DefaultValue, (FrameworkPropertyMetadataOptions)256, PropertyChangedCallback, CoerceValueCallback));
        
    }
}";

		TestSourceCodeTemplate(sourceCodeTemplate, expectedSourceCodeTemplate);
	}
}
