using Bindables.Test;
using NUnit.Framework;

namespace Bindables.Windows.Test;

public abstract partial class WindowsDependencyPropertyTests<T> : DependencyPropertyTests<T> where T : PropertyGeneratorBase, new()
{
	[Test]
	public void ReadOnlyProperty()
	{
		const string sourceCodeTemplate = @"
using PlatformNamespace;
using AttributeNamespace;

namespace Test
{
	public partial class ExampleClass : BaseClassName
	{
		[AttributeName(typeof(int))]
		private static readonly KeyPropertyType Example1PropertyKey;

		[AttributeName(typeof(string))]
		private static readonly KeyPropertyType Example2PropertyKey;
	}
}";

		const string expectedSourceCodeTemplate = @"
// Generated by Bindables
using PlatformNamespace;

#nullable enable

namespace Test
{
    public partial class ExampleClass
    {
        public static readonly PropertyType Example1Property;

        public int Example1
        {
            get => (int)GetValue(Example1Property);
            private set => SetValue(Example1PropertyKey, value);
        }

        public static readonly PropertyType Example2Property;

        public string? Example2
        {
            get => (string?)GetValue(Example2Property);
            private set => SetValue(Example2PropertyKey, value);
        }

        static ExampleClass()
        {
            Example1PropertyKey = PropertyType.RegisterReadOnly(
                ""Example1"",
                typeof(int),
                typeof(ExampleClass),
                new FrameworkPropertyMetadata());
            
            Example1Property = Example1PropertyKey.PropertyType;
            
            Example2PropertyKey = PropertyType.RegisterReadOnly(
                ""Example2"",
                typeof(string),
                typeof(ExampleClass),
                new FrameworkPropertyMetadata());
            
            Example2Property = Example2PropertyKey.PropertyType;
            
        }
    }
}";

		TestSourceCodeTemplate(sourceCodeTemplate, expectedSourceCodeTemplate);
	}
}