using System.Linq;
using Bindables.Test;
using NUnit.Framework;

namespace Bindables.Wpf.Test.AttachedProperty;

[TestFixture]
public class ReadOnlyProperty : WpfTestBase
{
	private const string SourceCode = @"
using System.Windows;
using Bindables.Wpf;

namespace Test
{
	public partial class WpfClass
	{
		[AttachedProperty(typeof(int))]
		private static readonly DependencyPropertyKey ExamplePropertyKey;
	}
}";

	private const string ExpectedSourceCode = @"
// Generated by Bindables
using System.Windows;

namespace Test
{
    public partial class WpfClass
    {
        public static readonly DependencyProperty ExampleProperty;

        public static int GetExample(DependencyObject target)
        {
            return (int)target.GetValue(ExampleProperty);
        }

        private static void SetExample(DependencyObject target, int value)
        {
            target.SetValue(ExampleProperty, value);
        }

        static WpfClass()
        {
            ExamplePropertyKey = DependencyProperty.RegisterAttachedReadOnly(
                ""Example"",
                typeof(int),
                typeof(WpfClass),
                new FrameworkPropertyMetadata());
            
            ExampleProperty = ExamplePropertyKey.DependencyProperty;
            
        }
    }
}";

	[Test]
	public void Test()
	{
		TestResult result = Generate<AttachedPropertyGenerator>(SourceCode);
		CheckResult(result);
		
		Assert.That(result.SyntaxTrees, Has.Count.EqualTo(1));
		Assert.That(result.SyntaxTrees.Single().ToString().Trim(), Is.EqualTo(ExpectedSourceCode.Trim()));
	}
}