using System.Linq;
using Bindables.Test;
using NUnit.Framework;

namespace Bindables.Wpf.Test.AttachedProperty;

[TestFixture]
public class SimpleProperty : WpfTestBase
{
	private const string SourceCode = @"
using System.Windows;
using Bindables.Wpf;

public partial class WpfClass
{
    private static readonly string DefaultValue = ""Test"";

	[AttachedProperty(typeof(int))]
	public static readonly DependencyProperty Example1Property;

	[AttachedProperty(typeof(int), OnPropertyChanged = nameof(PropertyChangedCallback))]
	public static readonly DependencyProperty Example2Property;

	[AttachedProperty(typeof(string), DefaultValueField = nameof(DefaultValue))]
	public static readonly DependencyProperty Example3Property;

	[AttachedProperty(typeof(string), Options = FrameworkPropertyMetadataOptions.BindsTwoWayByDefault)]
	public static readonly DependencyProperty Example4Property;

	[AttachedProperty(typeof(string), OnPropertyChanged = nameof(PropertyChangedCallback), DefaultValueField = nameof(DefaultValue))]
	public static readonly DependencyProperty Example5Property;

	[AttachedProperty(typeof(string), OnPropertyChanged = nameof(PropertyChangedCallback), DefaultValueField = nameof(DefaultValue), Options = FrameworkPropertyMetadataOptions.BindsTwoWayByDefault)]
	public static readonly DependencyProperty Example6Property;

    private static void PropertyChangedCallback(DependencyObject obj, DependencyPropertyChangedEventArgs args)
    {
    }
}";

	private const string ExpectedSourceCode = @"
// Generated by Bindables
using System.Windows;

public partial class WpfClass
{
    public static int GetExample1(DependencyObject target)
    {
        return (int)target.GetValue(Example1Property);
    }

    public static void SetExample1(DependencyObject target, int value)
    {
        target.SetValue(Example1Property, value);
    }

    public static int GetExample2(DependencyObject target)
    {
        return (int)target.GetValue(Example2Property);
    }

    public static void SetExample2(DependencyObject target, int value)
    {
        target.SetValue(Example2Property, value);
    }

    public static string GetExample3(DependencyObject target)
    {
        return (string)target.GetValue(Example3Property);
    }

    public static void SetExample3(DependencyObject target, string value)
    {
        target.SetValue(Example3Property, value);
    }

    public static string GetExample4(DependencyObject target)
    {
        return (string)target.GetValue(Example4Property);
    }

    public static void SetExample4(DependencyObject target, string value)
    {
        target.SetValue(Example4Property, value);
    }

    public static string GetExample5(DependencyObject target)
    {
        return (string)target.GetValue(Example5Property);
    }

    public static void SetExample5(DependencyObject target, string value)
    {
        target.SetValue(Example5Property, value);
    }

    public static string GetExample6(DependencyObject target)
    {
        return (string)target.GetValue(Example6Property);
    }

    public static void SetExample6(DependencyObject target, string value)
    {
        target.SetValue(Example6Property, value);
    }

    static WpfClass()
    {
        Example1Property = DependencyProperty.RegisterAttached(
            ""Example1"",
            typeof(int),
            typeof(WpfClass),
            new PropertyMetadata());
        
        Example2Property = DependencyProperty.RegisterAttached(
            ""Example2"",
            typeof(int),
            typeof(WpfClass),
            new PropertyMetadata(PropertyChangedCallback));
        
        Example3Property = DependencyProperty.RegisterAttached(
            ""Example3"",
            typeof(string),
            typeof(WpfClass),
            new PropertyMetadata(DefaultValue));
        
        Example4Property = DependencyProperty.RegisterAttached(
            ""Example4"",
            typeof(string),
            typeof(WpfClass),
            new FrameworkPropertyMetadata(default, (FrameworkPropertyMetadataOptions)256));
        
        Example5Property = DependencyProperty.RegisterAttached(
            ""Example5"",
            typeof(string),
            typeof(WpfClass),
            new PropertyMetadata(DefaultValue, PropertyChangedCallback));
        
        Example6Property = DependencyProperty.RegisterAttached(
            ""Example6"",
            typeof(string),
            typeof(WpfClass),
            new FrameworkPropertyMetadata(DefaultValue, (FrameworkPropertyMetadataOptions)256, PropertyChangedCallback));
        
    }
}";

	[Test]
	public void Test()
	{
		TestResult result = Generate<AttachedPropertyGenerator>(SourceCode);
		CheckResult(result);

		Assert.That(result.SyntaxTrees, Has.Count.EqualTo(1));
		Assert.That(result.SyntaxTrees.Single().ToString().Trim(), Is.EqualTo(ExpectedSourceCode.Trim()));
	}
}