using NUnit.Framework;

namespace Bindables.Xamarin.Test;

public abstract partial class XamarinTests<T>
{
	[Test]
	public void RegularProperty()
	{
		string sourceCode = $@"
using {PlatformNamespace};
using {AttributeNamespace};

public partial class ExampleClass : {BaseClassName}
{{
    private static readonly string DefaultValue = ""Test"";

	[{DependencyPropertyAttributeName}(typeof(int))]
	public static readonly {DependencyPropertyName} Example1Property;

	[{DependencyPropertyAttributeName}(typeof(int), OnPropertyChanged = nameof(PropertyChangedCallback))]
	public static readonly {DependencyPropertyName} Example2Property;

	[{DependencyPropertyAttributeName}(typeof(string), DefaultValueField = nameof(DefaultValue))]
	public static readonly {DependencyPropertyName} Example3Property;

	[{DependencyPropertyAttributeName}(typeof(string), BindingMode = BindingMode.OneTime)]
	public static readonly {DependencyPropertyName} Example4Property;

	[{DependencyPropertyAttributeName}(typeof(string), OnPropertyChanged = nameof(PropertyChangedCallback), DefaultValueField = nameof(DefaultValue))]
	public static readonly {DependencyPropertyName} Example5Property;

	[{DependencyPropertyAttributeName}(typeof(string), OnPropertyChanged = nameof(PropertyChangedCallback), DefaultValueField = nameof(DefaultValue), BindingMode = BindingMode.OneTime)]
	public static readonly {DependencyPropertyName} Example6Property;

    private static void PropertyChangedCallback({BaseClassName} obj, object oldValue, object newValue)
    {{
    }}

    // ATTACHED

    private static readonly string DefaultValueAttached = ""Test"";

	[{AttachedPropertyAttributeName}(typeof(int))]
	public static readonly {DependencyPropertyName} ExampleAttached1Property;

	[{AttachedPropertyAttributeName}(typeof(int), OnPropertyChanged = nameof(PropertyChangedCallbackAttached))]
	public static readonly {DependencyPropertyName} ExampleAttached2Property;

	[{AttachedPropertyAttributeName}(typeof(string), DefaultValueField = nameof(DefaultValue))]
	public static readonly {DependencyPropertyName} ExampleAttached3Property;

	[{AttachedPropertyAttributeName}(typeof(string), BindingMode = BindingMode.OneTime)]
	public static readonly {DependencyPropertyName} ExampleAttached4Property;

	[{AttachedPropertyAttributeName}(typeof(string), OnPropertyChanged = nameof(PropertyChangedCallbackAttached), DefaultValueField = nameof(DefaultValueAttached))]
	public static readonly {DependencyPropertyName} ExampleAttached5Property;

	[{AttachedPropertyAttributeName}(typeof(string), OnPropertyChanged = nameof(PropertyChangedCallbackAttached), DefaultValueField = nameof(DefaultValueAttached), BindingMode = BindingMode.OneTime)]
	public static readonly {DependencyPropertyName} ExampleAttached6Property;

    private static void PropertyChangedCallbackAttached({BaseClassName} obj, object oldValue, object newValue)
    {{
    }}
}}";

		string expectedSourceCode = $@"
// Generated by Bindables
using {PlatformNamespace};

#nullable enable

public partial class ExampleClass
{{
    public int Example1
    {{
        get => (int)GetValue(Example1Property);
        set => SetValue(Example1Property, value);
    }}

    public int Example2
    {{
        get => (int)GetValue(Example2Property);
        set => SetValue(Example2Property, value);
    }}

    public string? Example3
    {{
        get => (string?)GetValue(Example3Property);
        set => SetValue(Example3Property, value);
    }}

    public string? Example4
    {{
        get => (string?)GetValue(Example4Property);
        set => SetValue(Example4Property, value);
    }}

    public string? Example5
    {{
        get => (string?)GetValue(Example5Property);
        set => SetValue(Example5Property, value);
    }}

    public string? Example6
    {{
        get => (string?)GetValue(Example6Property);
        set => SetValue(Example6Property, value);
    }}

    public static int GetExampleAttached1({BaseClassName} target)
    {{
        return (int)target.GetValue(ExampleAttached1Property);
    }}

    public static void SetExampleAttached1({BaseClassName} target, int value)
    {{
        target.SetValue(ExampleAttached1Property, value);
    }}

    public static int GetExampleAttached2({BaseClassName} target)
    {{
        return (int)target.GetValue(ExampleAttached2Property);
    }}

    public static void SetExampleAttached2({BaseClassName} target, int value)
    {{
        target.SetValue(ExampleAttached2Property, value);
    }}

    public static string? GetExampleAttached3({BaseClassName} target)
    {{
        return (string?)target.GetValue(ExampleAttached3Property);
    }}

    public static void SetExampleAttached3({BaseClassName} target, string? value)
    {{
        target.SetValue(ExampleAttached3Property, value);
    }}

    public static string? GetExampleAttached4({BaseClassName} target)
    {{
        return (string?)target.GetValue(ExampleAttached4Property);
    }}

    public static void SetExampleAttached4({BaseClassName} target, string? value)
    {{
        target.SetValue(ExampleAttached4Property, value);
    }}

    public static string? GetExampleAttached5({BaseClassName} target)
    {{
        return (string?)target.GetValue(ExampleAttached5Property);
    }}

    public static void SetExampleAttached5({BaseClassName} target, string? value)
    {{
        target.SetValue(ExampleAttached5Property, value);
    }}

    public static string? GetExampleAttached6({BaseClassName} target)
    {{
        return (string?)target.GetValue(ExampleAttached6Property);
    }}

    public static void SetExampleAttached6({BaseClassName} target, string? value)
    {{
        target.SetValue(ExampleAttached6Property, value);
    }}

    static ExampleClass()
    {{
        Example1Property = {DependencyPropertyName}.Create(
            ""Example1"",
            typeof(int),
            typeof(ExampleClass),
            default);
        
        Example2Property = {DependencyPropertyName}.Create(
            ""Example2"",
            typeof(int),
            typeof(ExampleClass),
            default,
            propertyChanged: PropertyChangedCallback);
        
        Example3Property = {DependencyPropertyName}.Create(
            ""Example3"",
            typeof(string),
            typeof(ExampleClass),
            DefaultValue);
        
        Example4Property = {DependencyPropertyName}.Create(
            ""Example4"",
            typeof(string),
            typeof(ExampleClass),
            default,
            defaultBindingMode: (BindingMode)4);
        
        Example5Property = {DependencyPropertyName}.Create(
            ""Example5"",
            typeof(string),
            typeof(ExampleClass),
            DefaultValue,
            propertyChanged: PropertyChangedCallback);
        
        Example6Property = {DependencyPropertyName}.Create(
            ""Example6"",
            typeof(string),
            typeof(ExampleClass),
            DefaultValue,
            defaultBindingMode: (BindingMode)4,
            propertyChanged: PropertyChangedCallback);
        
        ExampleAttached1Property = {DependencyPropertyName}.CreateAttached(
            ""ExampleAttached1"",
            typeof(int),
            typeof(ExampleClass),
            default);
        
        ExampleAttached2Property = {DependencyPropertyName}.CreateAttached(
            ""ExampleAttached2"",
            typeof(int),
            typeof(ExampleClass),
            default,
            propertyChanged: PropertyChangedCallbackAttached);
        
        ExampleAttached3Property = {DependencyPropertyName}.CreateAttached(
            ""ExampleAttached3"",
            typeof(string),
            typeof(ExampleClass),
            DefaultValue);
        
        ExampleAttached4Property = {DependencyPropertyName}.CreateAttached(
            ""ExampleAttached4"",
            typeof(string),
            typeof(ExampleClass),
            default,
            defaultBindingMode: (BindingMode)4);
        
        ExampleAttached5Property = {DependencyPropertyName}.CreateAttached(
            ""ExampleAttached5"",
            typeof(string),
            typeof(ExampleClass),
            DefaultValueAttached,
            propertyChanged: PropertyChangedCallbackAttached);
        
        ExampleAttached6Property = {DependencyPropertyName}.CreateAttached(
            ""ExampleAttached6"",
            typeof(string),
            typeof(ExampleClass),
            DefaultValueAttached,
            defaultBindingMode: (BindingMode)4,
            propertyChanged: PropertyChangedCallbackAttached);
        
    }}
}}";

		TestSourceCodeTemplate(sourceCode, expectedSourceCode);
	}
}
