using System.Linq;
using Bindables.Test;
using NUnit.Framework;

namespace Bindables.Wpf.Test.DependencyProperty;

[TestFixture]
public class ReadOnlyProperty : WpfTestBase
{
	private const string SourceCode = @"
using System.Windows;
using Bindables.Wpf;

namespace Test
{
	public partial class WpfClass : DependencyObject
	{
		[DependencyProperty(typeof(int))]
		public static readonly DependencyPropertyKey ExamplePropertyKey;
	}
}";

	private const string ExpectedSourceCode = @"
// Generated by Bindables
using System.Windows;

namespace Test
{
    public partial class WpfClass
    {
        public static readonly DependencyProperty ExampleProperty;

        public int Example
        {
            get => (int)GetValue(ExampleProperty);
            private set => SetValue(ExamplePropertyKey, value);
        }

        static WpfClass()
        {
            ExamplePropertyKey = DependencyProperty.RegisterReadOnly(
                nameof(Example),
                typeof(int),
                typeof(WpfClass),
                new FrameworkPropertyMetadata());
            
            ExampleProperty = ExamplePropertyKey.DependencyProperty;
            
        }
    }
}";

	[Test]
	public void Test()
	{
		TestResult result = Generate<DependencyPropertyGenerator>(SourceCode);
		CheckResult(result);
		
		Assert.That(result.SyntaxTrees, Has.Count.EqualTo(1));
		Assert.That(result.SyntaxTrees.Single().ToString().Trim(), Is.EqualTo(ExpectedSourceCode.Trim()));
	}
}