using System;

namespace Bindables
{
	/// <summary>
	/// A marker exception that means the contents of the method will
	/// be generated by Bindables.
	/// </summary>
	public class WillBeImplementedByBindablesException : Exception
	{
	}
}