using System.Linq;
using Bindables.Test;
using NUnit.Framework;

namespace Bindables.Forms.Test.BindableProperty;

[TestFixture]
public class ReadOnlyProperty : FormsTestBase
{
	private const string SourceCode = @"
using Bindables.Forms;
using Xamarin.Forms;

namespace Test
{
	public partial class FormsClass : BindableObject
	{
		[BindableProperty(typeof(int))]
		private static readonly BindablePropertyKey ExamplePropertyKey;
	}
}";

	private const string ExpectedSourceCode = @"
// Generated by Bindables
using Xamarin.Forms;

namespace Test
{
    public partial class FormsClass
    {
        public static readonly BindableProperty ExampleProperty;

        public int Example
        {
            get => (int)GetValue(ExampleProperty);
            private set => SetValue(ExamplePropertyKey, value);
        }

        static FormsClass()
        {
            ExamplePropertyKey = BindableProperty.CreateReadOnly(
                nameof(Example),
                typeof(int),
                typeof(FormsClass),
                default);
            
            ExampleProperty = ExamplePropertyKey.BindableProperty;
            
        }
    }
}";

	[Test]
	public void Test()
	{
		TestResult result = Generate<BindablePropertyGenerator>(SourceCode);
		CheckResult(result);
		
		Assert.That(result.SyntaxTrees, Has.Count.EqualTo(1));
		Assert.That(result.SyntaxTrees.Single().ToString().Trim(), Is.EqualTo(ExpectedSourceCode.Trim()));
	}
}